name: A workflow for my Course Work App
on: push

jobs:
  build:
    name: Course Work action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge dev-ops-gp-1
          docker pull mongo
          docker run -d --name mongo-dbserver --network dev-ops-gp-1 mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t dev-ops-gp-1 .
      - name: Run image
        run: docker run --network dev-ops-gp-1 --name semcontainer dev-ops-gp-1
      - name: view logs
        run: docker logs semcontainer